Fix AttributeError: 'module' object has no attribute 'finders'
Jenkins crashed because newer versions of setuptools do not have finders attibute.
Added control 'hasattr' for 'sdist.finders' before deleting it.