New command-line option `-p` to specify the max nr. of concurrently-started nodes.
This commit introduces a new command-line option
`-p`/`--max-concurrent-request` to `elasticluster start` which allows
controlling the size of the thread pool used for issuing requests to
the cloud controller API.

Fix "AttributeError: 'Start' object has no attribute 'parallel'"
as reported by @verdurin in https://github.com/gc3-uzh-ch/elasticluster/pull/503#issuecomment-343248702